import './globals.css'
import { i18n } from '@/i18n-config'
import { cookies } from 'next/headers'
import Providers from '@/components/providers'
import Layout from '@/components/layout/layout'

export const metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
  icons: {
    icon: '/static/favicon.ico',
  },
}

export default function RootLayout({ children, params }) {

  const cookieStore = cookies();
  const theme = cookieStore.get('theme');

  return (
    <html lang={params.lang} {...(theme?.value && { 'data-theme': theme.value })} suppressHydrationWarning>
      <head>
        <meta charSet="utf-8" />
        <link rel="manifest" href="/static/logo/site.webmanifest" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body>
        <Providers>
          <Layout>
            {children}
          </Layout>
        </Providers>
      </body>
    </html>
  )
}

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }))
}
